version: "3.9"
   
services:
  interface:
    build:
      context: ../
      dockerfile: interface-dnabarcoder/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

  celery:
    build:
      context: ../
      dockerfile: interface-dnabarcoder/Dockerfile
    command: celery -A interface-dnabarcoder worker -l INFO
    volumes:
      - .:/home/app
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build:
      context: ../
      dockerfile: interface-dnabarcoder/Dockerfile
    command: celery -A interface-dnabarcoder beat -l INFO
    volumes:
      - .:/home/app
    env_file:
      - .env
    depends_on:
      - redis

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: dnabarcoder.com
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
    cap_add:
        - NET_ADMIN
    restart: always