version: "3.9"
   
services:
  web:
    build:
      context: ../
      dockerfile: interface-dnabarcoder/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app
    ports:
      - "8000:8000"