version: "3.9"
   
services:
  interface:
    build:
      context: ../
      dockerfile: interface-dnabarcoder/Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/home/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

  celery:
    build:
      context: ../
      dockerfile: interface-dnabarcoder/Dockerfile
    command: celery -A interface-dnabarcoder worker -l INFO
    volumes:
      - .:/home/app
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build:
      context: ../
      dockerfile: interface-dnabarcoder/Dockerfile
    command: celery -A interface-dnabarcoder beat -l INFO
    volumes:
      - .:/home/app
    env_file:
      - .env
    depends_on:
      - redis
